services:
  industrial-facility-parameter-bus-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ifpba-api
    ports:
      - "8080:8080"
    environment:
      MQTT_BROKER_URL: tcp://eclipse-mosquitto:1883
      MQTT_CLIENT_ID: industrial-facility-parameter-bus-api
      MQTT_TOPIC: sensors/data
      MQTT_USERNAME: ""
      MQTT_PASSWORD: ""
    depends_on:
      - eclipse-mosquitto
    networks:
      - ifpba-net

  eclipse-mosquitto:
    image: eclipse-mosquitto:2
    container_name: ifpba-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - ifpba-net

  test-producer:
    image: eclipse-mosquitto:2
    container_name: ifpba-test-producer
    depends_on:
      - eclipse-mosquitto
    networks:
      - ifpba-net
    command:
      - sh
      - -c
      - |
        sleep 5
  
        while true; do
          mosquitto_pub \
            -h eclipse-mosquitto \
            -p 1883 \
            -t sensors/data \
            -m '{"pump_station_1":{"inlet_pressure":2.41,"outlet_pressure":5.87,"flow_rate_m3h":128.6},"water_treatment_1":{"osmosis_status":1.0,"conductivity":412.5},"power_unit_1":{"active_power_kw":12.7,"frequency_hz":50.0}}'
  
          echo "published"
  
          sleep 300
        done

networks:
  ifpba-net:
    driver: bridge